version: '3'
services:
  spark:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-spark-1 
    environment:
      - SPARK_MASTER_HOST=spark-spark-1
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'  
      - '7077:7077'  
    volumes:
      - ./scripts/:/opt/application/scripts/
    networks:
      - nyc-network

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-spark-worker-1 
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-spark-1:7077  
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark
    networks:
      - nyc-network

networks:
  nyc-network:
    external: true  
